endpoint-checker:
  sync-time: 1s
  threads: 100
  threads-naming: 'Pool-EndpointChecker-Thread-%d'
  page-size: 1000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moz_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 1
      data-source-properties:
        stringtype: unspecified
