endpoint-checker:
  sync-time: 1s
  threads: 100
  page-size: 300

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/local_moz_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 1
      data-source-properties:
        stringtype: unspecified
