adaptor:
  host: http://<ip>:<port>
  sync-time: 10000

endpoint:
  ip-info: 'http://ip-api.com/json/%s?fields=status,message,continent,continentCode,country,countryCode,region,regionName,city,district,zip,lat,lon,timezone,offset,isp,org,as,asname,hosting,query'
  lcd:
    node-info: '/node_info'

spring:
  main:
    web-application-type: none

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY


