endpoint:
  lcd:
    node-info: '/node_info'
    new-node-info: '/cosmos/base/tendermint/v1beta1/node_info'
    blocks-latest: '/blocks/latest'
    new-blocks-latest: '/cosmos/base/tendermint/v1beta1/blocks/latest'

spring:
  main:
    web-application-type: none

    jpa:
      open-in-view: false

      hibernate:
        ddl-auto: validate

      properties:
        hibernate:
          schema_update:
            unique_constraint_strategy: RECREATE_QUIETLY
          jdbc:
            lob:
              non_contextual_creation: true

