adaptor:
  host: http://<ip>:<port>
  sync-time: 10000

spring:
  main:
    web-application-type: none

    jpa:
      open-in-view: false

      hibernate:
        ddl-auto: validate

      properties:
        hibernate:
          schema_update:
            unique_constraint_strategy: RECREATE_QUIETLY
          jdbc:
            lob:
              non_contextual_creation: true

