endpoint-checker:
  sync-time: ${EC_SYNC_TIME}
  threads: ${EC_THREADS}
  threads-naming: 'Pool-EndpointChecker-Thread-%d'

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      data-source-properties:
        stringtype: unspecified
