endpoint-checker:
  sync-time: 10s
  threads: 100
  time-intervals: 'pt2m:p1d:300;pt5h:p10d:300;pt24h:p30d:300;pt48h:p60d:300;p90d:-:300'

location-finder:
  sync-time: 120s
  location-frequency-check: 30d

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moz_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 1
