endpoint-checker:
  sync-time: 60s
  threads: 8
  threads-naming: 'Pool-EndpointChecker-Thread-%d'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moz_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 8
      data-source-properties:
        stringtype: unspecified
